### PR TITLE
arm-none-eabi-binutils: new formula

### PR DESCRIPTION
**Pull request by fauxpark**
#29

### CODE REVIEW

**Comment by ladislas** [comment]
it is ready to merge? let me know :)

**Comment by fauxpark** [comment]
Yep, should be good to go. Seems the `conflicts_with`s can't really be set up properly, because all of the `arm-gcc-bin`s are versioned, and brew audit doesn't like that. Oh well.

**Comment by ladislas** [comment]
I think the fix would be to have the default version as arm-gcc-bin and make an alias of that instead of the other way around.

I'll merge this for now, we can modify the rest later

**Comment by ladislas** [comment]
@fauxpark something went wrong :(

**Comment by fauxpark** [comment]
I guess the bot still considers the arm-gcc-bin formulae modified even though I reverted the changes to them. One sec.

**Comment by fauxpark** [comment]
Also just noticed this tap has the same issue as in https://github.com/osx-cross/homebrew-avr/issues/270

**Comment by ladislas** [comment]
> Also just noticed this tap has the same issue as in https://github.com/osx-cross/homebrew-avr/issues/270

Fixed with 307759cacbd81d644dc2b01aaf4add1b9e50590a

**Comment by ladislas** [comment]
~~@fauxpark can you rebase on master so that it will build correctly? :)~~

actually I was able to do it!

**Pull request closed without merging**
