### PR TITLE
Update to 10.3-2021.10 release

### PR DESCRIPTION
**Pull request by chris-durand**
Update to the 10.3-2021.10 release

@ladislas

### CODE REVIEW

**Comment by ladislas** [comment]
Thank @chris-durand! Running CI, I'll merge as soon as all checks green

**Comment by ladislas** [comment]
@chris-durand there's a small style/audit issue, can you fix it and fixup?

**Comment by chris-durand** [comment]
> @chris-durand there's a small style/audit issue, can you fix it and fixup?

I have removed the line, as requested by the CI.

**Comment by ladislas** [comment]
Thanks for the PR! :)

**Pull request closed without merging**
