### PR TITLE
Fix style and rename versioned formulae

### PR DESCRIPTION
**Pull request by samford**
I came across this tap while checking if the ARMmbed/formulae tap had updated to the latest `arm-none-eabi` version and figured I would help with some improvements here.

This PR does the following:

* Fixes `brew style` offenses, bringing the formula style up to date.
* Renames `arm-gcc-bin@8` to `arm-gcc-bin@8-2019-q3-update` and `arm-gcc-bin@9` to `arm-gcc-bin@9-2020-q2-update`. The previous formula naming convention would become a problem the next time there's a release in August or September. I figured it would be best to use the full version here, so users can install the exact version they need. [If only the date part was used (e.g., `6-2017`) it would only be possible to have one of two releases with the same month/date, like `6-2017-q1-update` and `6-2017-q2-update`.]
* Adds an `arm-gcc-bin@9-2019-q4-major` formula for the sake of completeness, so all the stable releases from 2019 onward are available. It's easy to create additional versioned formulae for the remaining releases from the [downloads page](https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-rm/downloads) if anyone has any interest in that.
* Improves the `README` a bit.

Let me know if this needs any changes.

### CODE REVIEW

**Comment by ladislas** [comment]
Thanks a lot @samford for the PR and the nice cleanup! :) 

Are you a user yourself? What's your take on having v10 the default? Should we keep v9 for the moment?

For https://github.com/osx-cross/homebrew-avr, we kept v9 as default to let people experiment with v10 if needed.

For ARM, I've been using v10 since it came out with no significant changes, so I'm happy to keep it as it is.

**Comment by samford** [comment]
> Are you a user yourself? What's your take on having v10 the default? Should we keep v9 for the moment?

I haven't started using this yet, so I don't have any special insight on `9-2020-q2-update` vs. `10-2020-q4-major`. From a Homebrew perspective, first-party taps (e.g., homebrew/core, homebrew/cask) aim to use the latest version in the formula and sometimes provide versioned alternatives. However, third-party taps can do whatever they feel is most appropriate.

One way to approach this that could make everyone happy is to:

1. Convert `arm-gcc-bin` to a versioned `arm-gcc-bin@10-2020-q4-major` formula.
2. Create an `Aliases/arm-gcc-bin` symlink that points to `arm-gcc-bin@10-2020-q4-major.rb`.
3. Continue to create a new versioned formula for each release and update the `arm-gcc-bin` symlink to point to the latest version.

Users who want to always use the latest version can simply install `arm-gcc-bin`. Alternatively, a user who wants to specifically use `10-2020-q4-major` without being updated to a newer version in the future can do so by using `brew install arm-gcc-bin@10-2020-q4-major`. This would allow users to decide what's most appropriate for their particular circumstance.

I pushed a couple more commits that implement the aforementioned changes, so you can see what I mean and test it out. What do you think about this setup?

**Comment by ladislas** [comment]
Thanks for the input! I'll review one last time tomorrow morning (it's late in France) and merge your  changes. Thanks again for the helpful hand! :)

**Comment by leojrfs** [comment]
Hey guys, sorry, I've just seen this.

I still find it useful to somehow keep the original versioning format and their respective formulae.

For example, NCS (Nordic's SDK based on zephyr) requires `arm-gcc-bin@9-2019-q4-major`, as does [Contiki](https://github.com/contiki-ng/homebrew-contiki-ng-arm). Older Contiki builds for instance, require `5-2015-q4-major`.

The great thing about this formulae repo is that all formulae are `keg_only`, meaning we can have all of those versions installed.

My proposition is then to keep all the formulae in with their original versioning string, but still linking them to the major gcc releases, like so:

- `arm-gcc-bin -> arm-gcc-bin@10 -> arm-gcc-bin@10-2020-q4-major`
- `arm-gcc-bin@10-2020-q2-preview`
- `arm-gcc-bin@9 -> arm-gcc-bin@9-2019-q4-major`
- `arm-gcc-bin@9-2019-q4-major`
- `arm-gcc-bin@8 -> arm-gcc-bin@8-2019-q3-update`

and so on...

@ladislas @samford, thoughts?

**Pull request merged**
