### PR TITLE
Add arm-gcc-bin@11

### PR DESCRIPTION
**Pull request by salkinium**
Add ARM 11.2-2022.02 toolchain

Should I also change the alias to point to the latest version?

### CODE REVIEW

**Comment by salkinium** [comment]
So maybe we need to skip this version, I get internal compiler errors when using it, which seems to be a known limitation?
https://bugs.launchpad.net/gcc-arm-embedded/+bug/1970029

**Comment by salkinium** [comment]
Seems to be a bit of a disaster…
https://developer.arm.com/Tools%20and%20Software/GNU%20Toolchain#Resources

**Comment by ladislas** [comment]
thanks for the pr @salkinium!

maybe @fauxpark can fix this by compiling from source as he is doing for gcc@8 & gcc@9

**Comment by salkinium** [comment]
ARM released a new version without the compiler bugs: ARM 11.3-2022.08 toolchain.

**Comment by ladislas** [comment]
@salkinium could you update the PR? :)

**Comment by salkinium** [comment]
Sorry, I rebased the old commit by accident.

**Comment by salkinium** [comment]
Do you want me to add a test block to satisfy the CI? Some simple main.c compilation to catch at least big internal compiler errors?

**Comment by ladislas** [comment]
> Do you want me to add a test block to satisfy the CI? Some simple main.c compilation to catch at least big internal compiler errors?

That would be great yes! 

I think that something like this would be enough as we are using ARM binaries, we are not building anything ourselves.

https://github.com/osx-cross/homebrew-avr/blob/5088b5f15eaa1820b77185eb4995977cfd4e2906/Formula/avr-binutils.rb#L70-L73

**Comment by salkinium** [comment]
I'm not familiar with ruby at all, so I'm poking in the dark about best practices etc. I also don't understand how to test the changes locally? Can you help me?

**Comment by ladislas** [comment]
@salkinium the output of `...-gcc -v` is a bit more verbose, so the assert was not working:

```
Using built-in specs.
COLLECT_GCC=arm-none-eabi-c++
COLLECT_LTO_WRAPPER=/opt/homebrew/Cellar/arm-gcc-bin@10/10.3-2021.10_1/bin/../lib/gcc/arm-none-eabi/10.3.1/lto-wrapper
Target: arm-none-eabi
Configured with: /tmp/jenkins-GCC-10-pipeline-338_20211018_1634516195/src/gcc/configure --target=arm-none-eabi --prefix=/tmp/jenkins-GCC-10-pipeline-338_20211018_1634516195/install-native --libexecdir=/tmp/jenkins-GCC-10-pipeline-338_20211018_1634516195/install-native/lib --infodir=/tmp/jenkins-GCC-10-pipeline-338_20211018_1634516195/install-native/share/doc/gcc-arm-none-eabi/info --mandir=/tmp/jenkins-GCC-10-pipeline-338_20211018_1634516195/install-native/share/doc/gcc-arm-none-eabi/man --htmldir=/tmp/jenkins-GCC-10-pipeline-338_20211018_1634516195/install-native/share/doc/gcc-arm-none-eabi/html --pdfdir=/tmp/jenkins-GCC-10-pipeline-338_20211018_1634516195/install-native/share/doc/gcc-arm-none-eabi/pdf --enable-languages=c,c++ --enable-plugins --disable-decimal-float --disable-libffi --disable-libgomp --disable-libmudflap --disable-libquadmath --disable-libssp --disable-libstdcxx-pch --disable-nls --disable-shared --disable-threads --disable-tls --with-gnu-as --with-gnu-ld --with-newlib --with-headers=yes --with-python-dir=share/gcc-arm-none-eabi --with-sysroot=/tmp/jenkins-GCC-10-pipeline-338_20211018_1634516195/install-native/arm-none-eabi --build=x86_64-apple-darwin10 --host=x86_64-apple-darwin10 --with-gmp=/tmp/jenkins-GCC-10-pipeline-338_20211018_1634516195/build-native/host-libs/usr --with-mpfr=/tmp/jenkins-GCC-10-pipeline-338_20211018_1634516195/build-native/host-libs/usr --with-mpc=/tmp/jenkins-GCC-10-pipeline-338_20211018_1634516195/build-native/host-libs/usr --with-isl=/tmp/jenkins-GCC-10-pipeline-338_20211018_1634516195/build-native/host-libs/usr --with-libelf=/tmp/jenkins-GCC-10-pipeline-338_20211018_1634516195/build-native/host-libs/usr --with-host-libstdcxx='-static-libgcc -Wl,-lstdc++ -lm' --with-pkgversion='GNU Arm Embedded Toolchain 10.3-2021.10' --with-multilib-list=rmprofile,aprofile
Thread model: single
Supported LTO compression algorithms: zlib
gcc version 10.3.1 20210824 (release) (GNU Arm Embedded Toolchain 10.3-2021.10)
```

I replaced it with

```
  test do
    system "true"
  end
```

to make it simpler.

#40 fixes this.

**Comment by salkinium** [comment]
Ah, I was trying to use substring matching and failed.
Your way is a simpler solution.

**Pull request closed without merging**
