### PR TITLE
arm-none-eabi-binutils 2.41

### PR DESCRIPTION
**Pull request by fauxpark**
Bumping to latest version & to trigger macOS 14 bottles.

### CODE REVIEW

**Comment by fauxpark** [comment]
Hm, Monterey failing with:
```
   ../../gold/output.cc:32:10: fatal error: 'uchar.h' file not found
  #include <uchar.h>
           ^~~~~~~~~
```

**Comment by fauxpark** [comment]
Someone else has run up against it: https://www.mail-archive.com/bug-binutils@gnu.org/msg46285.html

Perhaps for now we must hold off on 2.42, let's try 2.41 instead.

**Comment by fauxpark** [comment]
Now there seems to be an issue with generating `bfd.info`.

EDIT: phew, just needed to remove the >=Ventura check on texinfo.

**Comment by ladislas** [comment]
Is it okay to merge? :)

**Comment by fauxpark** [comment]
It's all green, go ahead.

**Pull request closed without merging**
